#! /bin/bash

echo "Executing './gradlew test'..."
./gradlew test

if [ $? -ne 0 ]; then
  echo "Unit tests failed. Aborting push..."
  exit 1
fi

echo "Unit tests passed. Proceeding with the push..."
exit 0
